apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: ticket-shop
build:
  local:
    push: false
  artifacts:
    - image: manuhdez/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*
